export const projects = [{
	id: 1,
	title: "Mock Up Delivery Website",
	description: "An exercise in which I used Next js and Tailwind Css to create a website for an imaginary company that produces and processes food. Using ISR & SSR, hybrid.",
	tools: "Next js, Tailwind Css",
	linkRepo: "https://github.com/dornescum/tailwind-nextJs-setup",
	linkPage: "https://tailwind-next-js-menu.vercel.app/",
	img: "@../../src/img/projects/mockUpMenu.webp",
	tagJs: "Next",
	tagCss: "Tailwind",
	tagTutorial: false
},
	{
		id: 2-15,
		title: "Movie search",
		description: "Fetching movies from DB and search for the movies",
		tools: "React js, Tailwind Css",
		linkRepo: "https://github.com/dornescum/moviedDb",
		linkPage: "https://movie-db-188e7.web.app/",
		img: "@../../src/img/projects/movieDb.webp",
		tagJs: "React",
		tagCss: "Tailwind",
		tagTutorial: false
	},
	{
		id: 2-23,
		title: "Working on it.. not ready",
		description: "Ecommerce, Next js, Node js",
		tools: "Next js, Tailwind Css",
		linkRepo: "",
		linkPage: "https://electronic-store-next-js.vercel.app/Phones",
		img: "@../../src/img/projects/ecommerce.webp",
		tagJs: "Next",
		tagCss: "Tailwind",
		tagTutorial: false
	},
	{
		id: 12,
		title: "Menu cart",
		description: "Context Api for state management.",
		tools: "React js, Tailwind Css",
		linkRepo: "https://github.com/dornescum/menu-cart",
		linkPage: "https://menu-cart-21724.web.app/",
		img: "@../../src/img/projects/menuCart.webp",
		tagJs: "React",
		tagCss: "Tailwind",
		tagTutorial: false
	},

	{
		id: 3,
		title: "Admin Panel",
		description: "An admin panel in which I tested Cypress together with React js.",
		tools: "React js, Styled-Components, Cypress, Context Api",
		linkRepo: "https://github.com/dornescum/adminPannel",
		linkPage: "",
		img: "@../../src/img/projects/cypress.webp",
		tagJs: "Cypress",
		tagCss: "Styled-Components",
		tagTutorial: false
	}, {
		id: 4,
		title: "Cypress testing FirmeCadastru.ro",
		description: "Cypress testing FirmeCadastru.ro",
		tools: "Cypress",
		linkRepo: "https://github.com/dornescum/FC",
		linkPage: "https://firmecadastru.ro/",
		img: "@../../src/img/projects/cypress.webp",
		tagJs: "Cypress",
		tagCss: "",
		tagTutorial: false
	},
	{
		id: 2,
		title: "Best Car Ever",
		description: "An exercise in which I used Next js and Scss to create a website where I sell a car.",
		tools: "Next js, Scss, Simple-react-lightbox, React Icons",
		linkRepo: "https://github.com/dornescum/car_next",
		linkPage: "https://car-next.vercel.app/",
		img: "@../../src/img/projects/opelDan.webp",
		tagJs: "Next",
		tagCss: "Scss",
		tagTutorial: false
	},
	{
		id: 2-17,
		title: "Search for images",
		description: "React, Unsplash api",
		tools: "React js, React-Icons, Tailwind css",
		linkRepo: "https://github.com/dornescum/unsplash-photos",
		linkPage: "",
		img: "@../../src/img/projects/searchPhoto.webp",
		tagJs: "React",
		tagCss: "Tailwind",
		tagTutorial: false
	},
	{
		id: 5,
		title: "Todo App",
		description: "A simple todo app with typescript , from freeCodeCamp.org.",
		tools: "Typescript",
		linkRepo: "https://github.com/dornescum/Todo-tsx",
		linkPage: "https://todo-app-cc92d.web.app/",
		img: "@../../src/img/projects/typescript.webp",
		tagJs: "React",
		tagCss: "Css",
		tagTs: "Typescript",
		tagTutorial: true
	}, {
		id: 6,
		title: "Card",
		description: "Basic article card, challenge from FrontEndMentor.io.",
		tools: "Html, Scss",
		linkRepo: "https://github.com/dornescum/FrontEndMentor-article",
		linkPage: "https://front-end-mentor-article.vercel.app/",
		img: "@../../src/img/projects/article_card.webp",
		tagJs: "Html",
		tagCss: "Scss",
		tagTutorial: false
	}, {
		id: 7,
		title: "Card",
		description: "Equilibrium card, challenge from FrontEndMentor.io.",
		tools: "Html, Scss",
		linkRepo: "https://github.com/dornescum/Frontend-mentor-NFT",
		linkPage: "https://nft-beige.vercel.app/",
		img: "@../../src/img/projects/challenge-card.webp",
		tagJs: "Html",
		tagCss: "Scss",
		tagTutorial: false
	}, {
		id: 8,
		title: "Google Clone",
		description: "Google clone exercise from <b>JavaScriptSMastery</b>, Context Api, useDebounce,Tailwind darkMode.",
		tools: "React js, Tailwind Css",
		linkRepo: "https://github.com/dornescum/google-clone-jsMastery",
		linkPage: "",
		img: "@../../src/img/projects/googl.webp",
		tagJs: "React",
		tagCss: "Tailwind",
		tagTutorial: true
	},
	{
		id: 10,
		title: "Vuetify",
		description: "Vue js and Vuetify, a Material Design Framework",
		tools: "Vue Js",
		linkRepo: "https://github.com/dornescum/retetarVue",
		linkPage: "",
		img: "@../../src/img/projects/vuetify.webp",
		tagJs: "Vue Js",
		tagCss: "Vuetify",
		tagTutorial: false
	},
	{
		id: 9,
		title: "You are looking at it 😃",
		description: "I am using Vanilla Js, ES6 modules with Tailwind Css.",
		tools: "Vanilla Js, Tailwind Css",
		linkRepo: "https://github.com/dornescum/Mihai-Dornescu",
		linkPage: "https://dornescum.github.io/Mihai-Dornescu/",
		img: "@../../src/img/projects/mihai-dornescu.webp",
		tagJs: "Javascript",
		tagCss: "Tailwind",
		tagTutorial: false
	},
	{
		id: 11,
		title: "Shopping Cart",
		description: "Context Api & useReducer for state management from <b>RoadsideCoder</b>",
		tools: "React js, React-Bootstrap",
		linkRepo: "https://github.com/dornescum/shoppingCart",
		linkPage: "",
		img: "@../../src/img/projects/shoppingCart.webp",
		tagJs: "React",
		tagCss: "Bootstrap",
		tagTutorial: true
	},
	{
		id: 13,
		title: "Add List",
		description: "React Typescript passing props, interface exercise from <b>Laith Harb</b>",
		tools: "React js, React-Bootstrap",
		linkRepo: "https://github.com/dornescum/react-props-typescript",
		linkPage: "",
		img: "@../../src/img/projects/typescript.webp",
		tagJs: "React",
		tagCss: "Tailwind",
		tagTs: "Typescript",
		tagTutorial: true
	},


];
