

export const projects = [
	{
		id: 2 - 23,
		title: "Meseriasi website",
		description:  "A full stack with seo",
		tools: "Angular 16, Universal Engine, Express js, Tailwind Css",
		linkRepo: "",
		linkPage: "http://62.171.167.229:4000/home",
		img: "@../../src/img/projects/angular2.webp",
		tagJs: "Angular",
		tagCss: "Tailwind",
		tagTutorial: false,
		desc: "Angular",
	},
	{
	id: 2 - 23,
	title: "Mockup Ecommerce, context api",
	description:  "Ecommerce, Next js, Node js <span style='color: #FF0000FF'><b>Because is a free service of node, it will take 15 sec to be online</b></span>",
	tools: "Next js, Tailwind Css",
	linkRepo: "",
	linkPage: "https://electronic-store-next-js.vercel.app/",
	img: "@../../src/img/projects/ecommerce.webp",
	tagJs: "Next",
	tagCss: "Tailwind",
	tagTutorial: false,
	desc: "Next js",
},
	{
		id: 1/5/2023,
		title: "Full stack admin panel",
		description:  "node js express, jsonwebtoken, md5, joi, sqlite, angular form, typescript, tailwind css",
		tools:"Node js, <span  style='color: #000000;'>Express</span>, Sqlite, <span  style='color: #ef3333;'>Angular</span>, Typescript",
		linkRepo: "https://github.com/dornescum/sqliteAdminPanel",
		linkPage: "http://62.171.167.229:4200/client/#/login",
		img: "@../../src/img/projects/adminPanel.GIF",
		tagJs: "Angular",
		tagCss: "Tailwind",
		tagTs: "Typescript",
		tagTutorial: false,
		tagDB: 'Sqlite',
		tagNode: true,
		desc: "Node js , Express, Sqlite, Angular",
	},
	{
		id: 8 - 25,
		title: "FastApi Todo",
		description: "CRUD app",
		tools: "FastApi, <span  style='color: #6b9e11;'>Python</span>, Sqlite, React",
		linkRepo: "https://github.com/dornescum/fastApi_Todo_React_Sqlite",
		linkPage: "",
		img: "@../../src/img/projects/todo_fastApi.webp",
		tagJs: "React",
		tagCss: "Bootstrap",
		tagTutorial: false,
		tagDB: 'Sqlite',
		tagPy: true,
		desc: "FastApi  Python, Sqlite, React",
	},
	{
		id: 15/8,
		title: " Ionic ecommerce simulator",
		description: "Ionic,Angular, Capacitor, @ngrx/store",
		tools: "<span  style='color: #ef3333;'>Angular</span>, Ionic, Typescript",
		linkRepo: "https://github.com/dornescum",
		linkPage: "https://ionic-lecommerce.web.app/login",
		img: "@../../src/img/projects/ionic-angular.webp",
		tagJs: "Angular",
		tagCss: "Css",
		tagTutorial: false,
		desc: "Ionic Angular",

	},
	{
		id: 7 - 8,
		title: "Todo App Jest testing",
		description: "Jest testing api, Supertest",
		tools: "Jest,SuperTest, <span  style='color: #000000;'>Express</span>, Sqlite",
		linkRepo: "https://github.com/dornescum/nodeJestTodo",
		linkPage: "",
		img: "@../../src/img/projects/jestTodo.webp",
		tagJs: "Express",
		tagCss: "Css",
		tagTutorial: false,
		tagDB: 'Sqlite',
		tagNode: true,
		desc: "Node js  Express Sqlite",
	},
	{
		id: 15 - 7,
		title: "Resume parser with python",
		description: "Pdf parser for certain words",
		tools: "Flask, spacy, pdfminer.six, pytest, <span  style='color: #6b9e11;'>Python</span>",
		linkRepo: "https://github.com/dornescum/resume_parser_py",
		linkPage: "",
		img: "@../../src/img/projects/resume_parser.webp",
		tagCss: "Css",
		tagTutorial: false,
		tagPy: true,
		desc: "Flask  spacy, pdfminer.six, pytest, Python",
	},
	{
		id: 2 - 15,
		title: "Movie search",
		description: "Fetching movies from DB and search for the movies",
		tools: "React js, Tailwind Css",
		linkRepo: "https://github.com/dornescum/moviedDb",
		linkPage: "https://movie-db-188e7.web.app/",
		img: "@../../src/img/projects/movieDb.webp",
		tagJs: "React",
		tagCss: "Tailwind",
		tagTutorial: false,
		desc: "React js  Tailwind Css",
	},
	{
		id: "09-08-23",
		title: "Admin panel ecommerce",
		description:  "node js express, jsonwebtoken, md5, express-validator, express-rate-limit, helmet, mysql, angular, primeng",
		tools:" <span  style='color: #000000;'>Express</span>, <span  style='color: #ef3333;'>Angular</span>, Mysql",
		linkRepo: "https://github.com/dornescum/quizExpressMysqlAngular",
		linkPage: "",
		img: "@../../src/img/projects/primeng-admin.gif",
		tagJs: "Angular",
		tagCss: "Primeng",
		tagTs: "Typescript",
		tagTutorial: false,
		tagDB: "Mysql",
		tagNode: true,
		desc: "Node js  Express, Mysql, Angular",
	},

	{
		id: 1,
		title: "Mock Up Delivery Website",
		description: " Next js and Tailwind Css to create a website for an imaginary company that produces and processes food. Using ISR & SSR, hybrid",
		tools: "Next js, Tailwind Css",
		linkRepo: "https://github.com/dornescum/tailwind-nextJs-setup",
		linkPage: "https://tailwind-next-js-menu.vercel.app/",
		img: "@../../src/img/projects/mockUpMenu.webp",
		tagJs: "Next",
		tagCss: "Tailwind",
		tagTutorial: false,
		desc: "Next js  React",
	},
	{
		id: '8-04-23',
		title: "Express server for Ecommerce",
		description: "Express routes for an ecommerce, on render",
		tools: "<span  style='color: #000000;'>Express</span>, Sqlite",
		linkRepo: "https://github.com/dornescum/node_Ecommerce_NextJs",
		linkPage: "",
		img: "@../../src/img/projects/nodejs.webp",
		tagJs: "Javascript",
		tagCss: "Css",
		tagTutorial: false,
		tagDB: 'Sqlite',
		tagNode: true,
		desc: "Node js  Express, Sqlite",
	},

	{
		id: 12,
		title: "Menu cart",
		description: "Context Api for state management",
		tools: "React js, Tailwind Css",
		linkRepo: "https://github.com/dornescum/menu-cart",
		linkPage: "https://menu-cart-21724.web.app/",
		img: "@../../src/img/projects/menuCart.webp",
		tagJs: "React",
		tagCss: "Tailwind",
		tagTutorial: false,
		desc: "React js  Tailwind Css",
	}, {
		id: 3 - 3,
		title: "Challenge",
		description: "FrontEndMentor challenge, Sunnyside agency landing page",
		tools: "React js, Tailwind Css",
		linkRepo: "https://github.com/dornescum/sunnySide-agency-FM",
		linkPage: "https://frontendmentor-sunnyagency.web.app/",
		img: "@../../src/img/projects/sunnyAgency.webp",
		tagJs: "React",
		tagCss: "Tailwind",
		tagTutorial: false,
		desc: "React js  Tailwind Css",
	}, {
		id: 3 - 8,
		title: "Challenge time-tracking",
		description: "FrontEndMentor challenge",
		tools: "Tailwind Css, Javascript",
		linkRepo: "https://github.com/dornescum/frontEndMentor-timeTracking",
		linkPage: "https://frontendm-timetracking.web.app/",
		img: "@../../src/img/projects/timeTracking.webp",
		tagJs: "Javascript",
		tagCss: "Tailwind",
		tagTutorial: false,
		desc: "Javascript  Tailwind Css",
	}, {
		id: 3 - 9,
		title: "Challenge accordion",
		description: "FrontEndMentor challenge",
		tools: "Tailwind Css, React js",
		linkRepo: "https://github.com/dornescum/frontEndMentor-accordionCard",
		linkPage: "https://frontendmentor-accordion.web.app//",
		img: "@../../src/img/projects/accordion.webp",
		tagJs: "React",
		tagCss: "Tailwind",
		tagTutorial: false,
		desc: "React js  Tailwind Css",
	}, {
		id: 3 - 13,
		title: "Challenge testimonial bootCamp",
		description: "FrontEndMentor challenge",
		tools: "Tailwind Css, Javascript",
		linkRepo: "https://github.com/dornescum/codingBootCamp-FEMentor",
		linkPage: "https://fem-bootcamptestimonials2.web.app/",
		img: "@../../src/img/projects/bootcamp.webp",
		tagJs: "Javascript",
		tagCss: "Tailwind",
		tagTutorial: false,
		desc: "Javascript  Tailwind Css",
	}, {
		id: 3 - 25,
		title: "Challenge count down timer",
		description: "FrontEndMentor challenge",
		tools: "Tailwind Css, Javascript",
		linkRepo: "https://github.com/dornescum/frontendMentor-countDownTimer",
		linkPage: "https://spiffy-cranachan-47ef3c.netlify.app/",
		img: "@../../src/img/projects/count_down_timer.webp",
		tagJs: "Javascript",
		tagCss: "Tailwind",
		tagTutorial: false,
		desc: "Javascript  Tailwind Css",
	}, {
		id: 3,
		title: "Admin Panel",
		description: "An admin panel in which I tested Cypress together with React js",
		tools: "React js, Styled-Components, Cypress, Context Api",
		linkRepo: "https://github.com/dornescum/adminPannel",
		linkPage: "",
		img: "@../../src/img/projects/cypress.webp",
		tagJs: "Cypress",
		tagCss: "Styled-Components",
		tagTutorial: false,
		desc: "React js Styled-Components, Cypress, Context Api",
	}, {
		id: 4,
		title: "Cypress testing FirmeCadastru.ro",
		description: "Cypress testing FirmeCadastru.ro",
		tools: "Cypress",
		linkRepo: "https://github.com/dornescum/FC",
		linkPage: "https://firmecadastru.ro/",
		img: "@../../src/img/projects/cypress.webp",
		tagJs: "Cypress",
		tagCss: "",
		tagTutorial: false,
		desc: "Cypress",
	}, {
		id: 2,
		title: "Best Car Ever",
		description: "An exercise in which I used Next js and Scss to create a website where I sell a car",
		tools: "Next js, Scss, Simple-react-lightbox, React Icons",
		linkRepo: "https://github.com/dornescum/car_next",
		linkPage: "https://car-next.vercel.app/",
		img: "@../../src/img/projects/opelDan.webp",
		tagJs: "Next",
		tagCss: "Scss",
		tagTutorial: false,
		desc: "Next js  Scss, Simple-react-lightbox, React Icons",
	}, {
		id: 2 - 17,
		title: "Search for images",
		description: "React, Unsplash api",
		tools: "React js, React-Icons, Tailwind css",
		linkRepo: "https://github.com/dornescum/unsplash-photos",
		linkPage: "",
		img: "@../../src/img/projects/searchPhoto.webp",
		tagJs: "React",
		tagCss: "Tailwind",
		tagTutorial: false,
		desc: "React js  React-Icons, Tailwind css",
	},
	{
		id: 6,
		title: "Card",
		description: "Basic article card, challenge from FrontEndMentor.io",
		tools: "Html, Scss",
		linkRepo: "https://github.com/dornescum/FrontEndMentor-article",
		linkPage: "https://front-end-mentor-article.vercel.app/",
		img: "@../../src/img/projects/article_card.webp",
		tagJs: "Html",
		tagCss: "Scss",
		tagTutorial: false,
		desc: "Html Scss",
	}, {
		id: 7,
		title: "Card",
		description: "Equilibrium card, challenge from FrontEndMentor.io",
		tools: "Html, Scss",
		linkRepo: "https://github.com/dornescum/Frontend-mentor-NFT",
		linkPage: "https://nft-beige.vercel.app/",
		img: "@../../src/img/projects/challenge-card.webp",
		tagJs: "Html",
		tagCss: "Scss",
		tagTutorial: false,
		desc: "Html Scss",
	}, {
		id: 3 - 4,
		title: "Challenge testimonials",
		description: "FrontEndMentor challenge, Testimonials, grid section ",
		tools: "Tailwind Css",
		linkRepo: "https://github.com/dornescum/testimonials-frontEndMentor",
		linkPage: "https://frontmentor-testimonials.web.app/",
		img: "@../../src/img/projects/testimonials.webp",
		tagJs: "",
		tagCss: "Tailwind",
		tagTutorial: false,
		desc: "Tailwind Css",
	},
	{
		id: 10,
		title: "Vuetify",
		description: "Vue js and Vuetify, a Material Design Framework",
		tools: "Vue Js",
		linkRepo: "https://github.com/dornescum/retetarVue",
		linkPage: "",
		img: "@../../src/img/projects/vuetify.webp",
		tagJs: "Vue Js",
		tagCss: "Vuetify",
		tagTutorial: false,
		desc: "Vue  and Vuetify, a Material Design Framework",
	}, {
		id: 9,
		title: "You are looking at it 😃",
		description: "I am using Vanilla Js, ES6 modules with Tailwind Css",
		tools: "Vanilla Js, Tailwind Css",
		linkRepo: "https://github.com/dornescum/Mihai-Dornescu",
		linkPage: "https://dornescum.github.io/Mihai-Dornescu/",
		img: "@../../src/img/projects/mihai-dornescu.webp",
		tagJs: "Javascript",
		tagCss: "Tailwind",
		tagTutorial: false,
		desc: "Javascript , Tailwind Css",
	},
	{
		id: 1 - 2,
		title: "My version of a resume",
		description: "Minimalist Resume",
		tools: "Scss, Javascript",
		linkRepo: "https://github.com/dornescum/cv-spa",
		linkPage: "https://dornescu.ro/",
		img: "@../../src/img/projects/dornescu-ro.webp",
		tagJs: "Javascript",
		tagCss: "Scss",
		tagTutorial: false,
		desc: "Javascript",
	},
	{
		id: 11 - 13 - 2022,
		title: "CRUD",
		description: "Simple node js. POST, PUT, GET, DELETE and use of <b  style='color: #6b9e11;'>sqlite</b> for database",
		tools: "Node js, Sqlite3 ",
		linkRepo: "https://github.com/dornescum/coursesHOME",
		linkPage: "",
		img: "@../../src/img/projects/nodejs.webp",
		tagJs: "Nodejs",
		tagCss: "",
		tagTs: "",
		tagTutorial: false,
		desc: "Node js , Sqlite3 ",
	},
	{
		id: 12/10/23,
		title: " Simple image recognition",
		description: "For good accuracy, use a photo with a face and good light.",
		tools: "<span  style='color: #ef3333;'>Angular</span>, Typescript, FaceApi.js",
		linkRepo: "https://github.com/dornescum/faceApiAngular",
		linkPage: "",
		img: "@../../src/img/projects/angular2.webp",
		tagJs: "Angular",
		tagCss: "Css",
		tagTutorial: false,
		desc: "Angular FaceApi.js , Typescript",

	}
];
